/**
 * Shared types for the testing-module runtime config layer.
 *
 * The string-literal unions mirror the database enums in
 * 20260428120000_testing_module_enums.sql verbatim. They are re-declared
 * here (rather than imported from `@/types/database`) so this module
 * doesn't depend on the autogenerated types being up to date.
 */

export type DirectionOfGood =
  | 'higher'
  | 'lower'
  | 'target_range'
  | 'context_dependent'

export type DefaultChart =
  | 'line'
  | 'bar'
  | 'radar'
  | 'asymmetry_bar'
  | 'target_zone'

export type ComparisonMode =
  | 'absolute'
  | 'bilateral_lsi'
  | 'vs_baseline'
  | 'vs_normative'

export type ClientPortalVisibility = 'auto' | 'on_publish' | 'never'

export type ClientViewChart =
  | 'line'
  | 'milestone'
  | 'bar'
  | 'narrative_only'
  | 'hidden'

export type InputType = 'decimal' | 'integer' | 'text' | 'file'

export type Side = 'left' | 'right' | null

/** Identifier for a single metric within a test. */
export interface MetricKey {
  testId: string
  metricId: string
}

/**
 * The five fields an EP can override per (org, test, metric).
 * NULL on any field means "use the schema default."
 */
export interface MetricRenderingHints {
  direction_of_good: DirectionOfGood
  default_chart: DefaultChart
  comparison_mode: ComparisonMode
  client_portal_visibility: ClientPortalVisibility
  client_view_chart: ClientViewChart
}

/**
 * Measurement attributes that are NOT overrideable per-EP. These come
 * from the schema (or a custom test definition) and are immutable for
 * a given test+metric.
 */
export interface MetricMeasurement {
  unit: string
  input_type: InputType
  /** True if the metric is bilateral (has left and right sides). */
  side_left_right: boolean
}

/**
 * Static labels for a metric. Used by the capture UI and Reports tab
 * to render category > subcategory > test > metric breadcrumbs.
 */
export interface MetricLabels {
  category_id: string
  category_name: string
  subcategory_id: string
  subcategory_name: string
  test_id: string
  test_name: string
  metric_id: string
  metric_label: string
}

/**
 * Result of resolveMetricSettings. Combines labels, measurement
 * attributes, resolved rendering hints, and a per-field record of
 * which fields came from an override (for the settings UI's `Custom`
 * badge).
 *
 * `is_custom` is true when the test_id points to a row in
 * practice_custom_tests rather than physical_markers_schema_seed.
 */
export interface ResolvedMetricSettings
  extends MetricLabels,
    MetricMeasurement,
    MetricRenderingHints {
  is_custom: boolean
  overrides: {
    direction_of_good: boolean
    default_chart: boolean
    comparison_mode: boolean
    client_portal_visibility: boolean
    client_view_chart: boolean
  }
}

/**
 * Shape of a row in physical_markers_schema_seed. Mirrors the table
 * exactly for use as the in-memory cache.
 */
export interface SchemaSeedRow extends MetricLabels, MetricMeasurement, MetricRenderingHints {}
