-- ============================================================================
-- 20260428121000_seed_physical_markers_v1_1_0
-- ============================================================================
-- Why: Populates physical_markers_schema_seed from
-- data/physical_markers_schema_v1.1.json (version 1.1.0).
-- This file is GENERATED — regenerate with:
--   node scripts/generate-physical-markers-seed.mjs
--
-- The seed is idempotent: TRUNCATE + INSERT runs on every apply, so
-- a re-applied migration ends with the same state regardless of
-- prior partial runs. Per-EP overrides in practice_test_settings
-- are unaffected — they're keyed on (test_id, metric_id) which
-- survive schema version bumps.
-- ============================================================================

-- Reset to a clean slate. ON DELETE CASCADE is not in play; this
-- is the simple approach to "make state match the JSON."
TRUNCATE TABLE physical_markers_schema_seed;

INSERT INTO physical_markers_schema_seed (
  category_id, category_name, category_display_order,
  subcategory_id, subcategory_name, subcategory_display_order, subcategory_notes,
  test_id, test_name, test_display_order, test_notes,
  metric_id, metric_label,
  unit, input_type, side_left_right,
  direction_of_good, default_chart, comparison_mode,
  client_portal_visibility, client_view_chart
) VALUES
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_flexion', 'Hip flexion', 1, NULL,
   'passive', 'Passive',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_flexion', 'Hip flexion', 1, NULL,
   'active', 'Active',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_ir_er', 'Hip IR / ER', 2, 'Measured supine and prone',
   'ir_supine', 'IR supine',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_ir_er', 'Hip IR / ER', 2, 'Measured supine and prone',
   'er_supine', 'ER supine',
   'deg', 'decimal', TRUE,
   'context_dependent'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_ir_er', 'Hip IR / ER', 2, 'Measured supine and prone',
   'ir_prone', 'IR prone',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_ir_er', 'Hip IR / ER', 2, 'Measured supine and prone',
   'er_prone', 'ER prone',
   'deg', 'decimal', TRUE,
   'context_dependent'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_hip', 'Hip', 1, NULL,
   'rom_hip_thomas', 'Thomas test (hip flexor length)', 3, NULL,
   'angle', 'Angle',
   'deg', 'decimal', TRUE,
   'lower'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_knee', 'Knee', 2, NULL,
   'rom_knee_flex_ext', 'Knee flexion / extension', 1, NULL,
   'flexion_passive', 'Flexion passive',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_knee', 'Knee', 2, NULL,
   'rom_knee_flex_ext', 'Knee flexion / extension', 1, NULL,
   'flexion_active', 'Flexion active',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_knee', 'Knee', 2, NULL,
   'rom_knee_flex_ext', 'Knee flexion / extension', 1, NULL,
   'extension_passive', 'Extension passive',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_knee', 'Knee', 2, NULL,
   'rom_knee_flex_ext', 'Knee flexion / extension', 1, NULL,
   'extension_active', 'Extension active',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_ankle', 'Ankle & foot', 3, NULL,
   'rom_ankle_df_lunge', 'Ankle dorsiflexion — weight-bearing lunge test', 1, NULL,
   'distance_cm', 'Wall distance',
   'cm', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_ankle', 'Ankle & foot', 3, NULL,
   'rom_ankle_df_lunge', 'Ankle dorsiflexion — weight-bearing lunge test', 1, NULL,
   'angle_deg', 'Angle',
   'deg', 'decimal', TRUE,
   'context_dependent'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_flex_ext', 'Shoulder flexion / extension', 1, NULL,
   'flexion', 'Flexion',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_flex_ext', 'Shoulder flexion / extension', 1, NULL,
   'extension', 'Extension',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_ir_er', 'Shoulder IR / ER', 2, 'Measured at 0° and 90° abduction',
   'ir_0deg', 'IR at 0°',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_ir_er', 'Shoulder IR / ER', 2, 'Measured at 0° and 90° abduction',
   'er_0deg', 'ER at 0°',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_ir_er', 'Shoulder IR / ER', 2, 'Measured at 0° and 90° abduction',
   'ir_90deg', 'IR at 90°',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_ir_er', 'Shoulder IR / ER', 2, 'Measured at 0° and 90° abduction',
   'er_90deg', 'ER at 90°',
   'deg', 'decimal', TRUE,
   'context_dependent'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_abd_add', 'Shoulder abduction / adduction', 3, NULL,
   'abduction', 'Abduction',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('rom', 'Range of motion', 1,
   'rom_shoulder', 'Shoulder', 4, NULL,
   'rom_shoulder_abd_add', 'Shoulder abduction / adduction', 3, NULL,
   'adduction', 'Adduction',
   'deg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'jump_height', 'Jump height',
   'cm', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'conc_peak_force', 'Concentric peak force',
   'N', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'ecc_peak_force', 'Eccentric peak force',
   'N', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'ecc_dec_rfd', 'Eccentric deceleration RFD',
   'N/s', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'peak_power', 'Peak power',
   'W', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_cmj', 'CMJ — bilateral', 1, NULL,
   'fp_cmj_bilateral', 'Countermovement jump', 1, NULL,
   'ft_ct', 'FT:CT ratio',
   'ratio', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_sj', 'Squat jump', 2, NULL,
   'fp_sj', 'Squat jump', 1, NULL,
   'jump_height', 'Jump height',
   'cm', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_dj', 'Drop jump', 3, NULL,
   'fp_dj_bilateral', 'Drop jump — bilateral', 1, NULL,
   'rsi', 'RSI',
   'm/s', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_unilateral', 'Unilateral jump', 4, NULL,
   'fp_slcmj', 'Single-leg CMJ', 1, NULL,
   'jump_height', 'Jump height',
   'cm', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_unilateral', 'Unilateral jump', 4, NULL,
   'fp_slcmj', 'Single-leg CMJ', 1, NULL,
   'lsi', 'LSI',
   '%', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_unilateral', 'Unilateral jump', 4, NULL,
   'fp_sl_dj', 'Single-leg drop jump', 2, NULL,
   'rsi', 'RSI',
   'm/s', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_unilateral', 'Unilateral jump', 4, NULL,
   'fp_sl_dj', 'Single-leg drop jump', 2, NULL,
   'contact_time', 'Contact time',
   'ms', 'decimal', TRUE,
   'lower'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_broad', 'Broad jump', 5, NULL,
   'fp_broad_jump', 'Broad jump', 1, NULL,
   'distance', 'Distance',
   'cm', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_isometric', 'Isometric', 6, NULL,
   'fp_imtp', 'IMTP', 1, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_isometric', 'Isometric', 6, NULL,
   'fp_imtp', 'IMTP', 1, NULL,
   'rfd_0_100', 'RFD 0–100ms',
   'N/s', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_isometric', 'Isometric', 6, NULL,
   'fp_imtp', 'IMTP', 1, NULL,
   'impulse', 'Impulse',
   'N·s', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_balance', 'Balance / postural', 7, NULL,
   'fp_cop_bilateral', 'Bilateral COP sway', 1, NULL,
   'eyes_open', 'Eyes open',
   'mm', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_balance', 'Balance / postural', 7, NULL,
   'fp_cop_bilateral', 'Bilateral COP sway', 1, NULL,
   'eyes_closed', 'Eyes closed',
   'mm', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('force_plate', 'Force plate', 2,
   'fp_balance', 'Balance / postural', 7, NULL,
   'fp_cop_unilateral', 'Unilateral COP sway', 2, NULL,
   'sway', 'Sway',
   'mm', 'decimal', TRUE,
   'lower'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_nordbord', 'NordBord — eccentric hamstrings', 1, NULL,
   'dyn_nordic', 'Nordic hamstring curl', 1, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_nordbord', 'NordBord — eccentric hamstrings', 1, NULL,
   'dyn_nordic', 'Nordic hamstring curl', 1, NULL,
   'lsi', 'LSI',
   '%', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_nordbord', 'NordBord — eccentric hamstrings', 1, NULL,
   'dyn_nordic', 'Nordic hamstring curl', 1, NULL,
   'force_angle_curve', 'Force-angle curve',
   'file', 'file', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_hip_abd', 'Hip abductor peak force', 1, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_hip_add', 'Hip adductor peak force', 2, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_add_abd_ratio', 'Adductor : abductor ratio', 3, NULL,
   'ratio', 'Ratio',
   'ratio', 'decimal', TRUE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_shoulder_er_ir', 'Shoulder ER/IR ratio', 4, NULL,
   'er_force', 'ER peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_shoulder_er_ir', 'Shoulder ER/IR ratio', 4, NULL,
   'ir_force', 'IR peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_shoulder_er_ir', 'Shoulder ER/IR ratio', 4, NULL,
   'ratio', 'ER:IR ratio',
   'ratio', 'decimal', TRUE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_knee_ext', 'Knee extension isometric peak force', 5, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_forceframe', 'ForceFrame — isometric', 2, NULL,
   'dyn_ff_knee_flex', 'Knee flexion isometric peak force', 6, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_dynamo', 'DynaMo — handheld dynamometry', 3, NULL,
   'dyn_hhd_knee_ext', 'Knee extension HHD', 1, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_dynamo', 'DynaMo — handheld dynamometry', 3, NULL,
   'dyn_hhd_knee_flex', 'Knee flexion HHD', 2, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_dynamo', 'DynaMo — handheld dynamometry', 3, NULL,
   'dyn_hhd_shoulder_abd', 'Shoulder abduction HHD', 3, NULL,
   'peak_force', 'Peak force',
   'N', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('dynamometry', 'Dynamometry', 3,
   'dyn_dynamo', 'DynaMo — handheld dynamometry', 3, NULL,
   'dyn_hhd_grip', 'Wrist grip strength', 4, NULL,
   'peak_force', 'Peak force',
   'kg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_dexa', 'DEXA', 1, NULL,
   'bc_dexa_scan', 'DEXA scan', 1, NULL,
   'total_lean_mass', 'Total lean mass',
   'kg', 'decimal', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_dexa', 'DEXA', 1, NULL,
   'bc_dexa_scan', 'DEXA scan', 1, NULL,
   'body_fat_pct', 'Body fat %',
   '%', 'decimal', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_dexa', 'DEXA', 1, NULL,
   'bc_dexa_scan', 'DEXA scan', 1, NULL,
   'vat', 'Visceral adipose tissue',
   'g', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_dexa', 'DEXA', 1, NULL,
   'bc_dexa_scan', 'DEXA scan', 1, NULL,
   'bmd', 'Bone mineral density (BMD)',
   'g/cm²', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_dexa', 'DEXA', 1, NULL,
   'bc_dexa_scan', 'DEXA scan', 1, NULL,
   't_score', 'T-score',
   'SD', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'body_mass', 'Body mass',
   'kg', 'decimal', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'height', 'Height',
   'cm', 'decimal', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'absolute'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'waist_circ', 'Waist circumference',
   'cm', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'hip_circ', 'Hip circumference',
   'cm', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'waist_hip_ratio', 'Waist-hip ratio',
   'ratio', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('body_composition', 'Body composition', 4,
   'bc_anthropometry', 'Anthropometry', 2, NULL,
   'bc_anthro', 'Anthropometric measures', 1, NULL,
   'thigh_circ', 'Thigh circumference',
   'cm', 'decimal', TRUE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_resting', 'Resting', 1, NULL,
   'cardio_resting_vitals', 'Resting vitals', 1, NULL,
   'hr', 'Resting heart rate',
   'bpm', 'integer', FALSE,
   'context_dependent'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_resting', 'Resting', 1, NULL,
   'cardio_resting_vitals', 'Resting vitals', 1, NULL,
   'bp_systolic', 'Systolic BP',
   'mmHg', 'integer', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_resting', 'Resting', 1, NULL,
   'cardio_resting_vitals', 'Resting vitals', 1, NULL,
   'bp_diastolic', 'Diastolic BP',
   'mmHg', 'integer', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_resting', 'Resting', 1, NULL,
   'cardio_resting_vitals', 'Resting vitals', 1, NULL,
   'spo2', 'SpO₂',
   '%', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_6mwt', '6-minute walk test', 1, NULL,
   'distance', 'Distance',
   'm', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_yoyo_ir2', 'Yo-Yo IR2', 2, NULL,
   'level', 'Level reached',
   'level', 'text', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_yoyo_ir2', 'Yo-Yo IR2', 2, NULL,
   'total_distance', 'Total distance',
   'm', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_beep', 'Beep test (20m shuttle)', 3, NULL,
   'level', 'Level reached',
   'level', 'text', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_beep', 'Beep test (20m shuttle)', 3, NULL,
   'vo2max_est', 'Estimated VO₂max',
   'mL/kg/min', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_step', 'Step test (Chester / Kasch)', 4, NULL,
   'hr_recovery', 'HR at 1min recovery',
   'bpm', 'integer', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_field', 'Submaximal / field', 2, NULL,
   'cardio_step', 'Step test (Chester / Kasch)', 4, NULL,
   'vo2max_est', 'Estimated VO₂max',
   'mL/kg/min', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_max', 'Maximal / lab', 3, NULL,
   'cardio_vo2max', 'VO₂max', 1, NULL,
   'vo2max_direct', 'VO₂max direct',
   'mL/kg/min', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('cardiorespiratory', 'Cardiorespiratory', 5,
   'cardio_max', 'Maximal / lab', 3, NULL,
   'cardio_vo2max', 'VO₂max', 1, NULL,
   'vo2max_estimated', 'VO₂max estimated',
   'mL/kg/min', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'vitamin_d', 'Vitamin D (25-OH)',
   'nmol/L', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'hba1c', 'HbA1c',
   '%', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'glucose', 'Fasting glucose',
   'mmol/L', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'cholesterol', 'Total cholesterol',
   'mmol/L', 'decimal', FALSE,
   'target_range'::direction_of_good_t, 'target_zone'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'ldl', 'LDL',
   'mmol/L', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('biomarkers', 'Biomarkers — blood & fluid', 6,
   'bio_metabolic', 'Metabolic / nutrition', 1, NULL,
   'bio_metabolic_panel', 'Metabolic & nutrition panel', 1, NULL,
   'hdl', 'HDL',
   'mmol/L', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_normative'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('neuromuscular', 'Neuromuscular & neurological', 7,
   'neuro_balance', 'Balance — clinical', 1, NULL,
   'neuro_sls', 'Single leg stance', 1, NULL,
   'eyes_open', 'Eyes open',
   's', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('neuromuscular', 'Neuromuscular & neurological', 7,
   'neuro_balance', 'Balance — clinical', 1, NULL,
   'neuro_sls', 'Single leg stance', 1, NULL,
   'eyes_closed', 'Eyes closed',
   's', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('functional_movement', 'Functional movement', 8,
   'func_upper', 'Upper limb functional', 1, NULL,
   'func_pushup', 'Push-up test', 1, NULL,
   'max_reps', 'Max reps',
   'reps', 'integer', FALSE,
   'higher'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('sport_performance', 'Sport-specific performance', 9,
   'sport_speed', 'Speed & sprint', 1, NULL,
   'sport_sprint_10m', '10m sprint', 1, NULL,
   'time', 'Time',
   's', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('sport_performance', 'Sport-specific performance', 9,
   'sport_speed', 'Speed & sprint', 1, NULL,
   'sport_sprint_20m', '20m sprint', 2, NULL,
   'time', 'Time',
   's', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('sport_performance', 'Sport-specific performance', 9,
   'sport_speed', 'Speed & sprint', 1, NULL,
   'sport_t_test', 'T-test (agility)', 3, NULL,
   'time', 'Time',
   's', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'line'::client_view_chart_t),
  ('sport_performance', 'Sport-specific performance', 9,
   'sport_generic', 'Generic capacity', 2, NULL,
   'sport_grip', 'Grip strength — bilateral', 1, NULL,
   'peak_force', 'Peak force',
   'kg', 'decimal', TRUE,
   'higher'::direction_of_good_t, 'asymmetry_bar'::default_chart_t, 'bilateral_lsi'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_pain', 'Pain', 1, NULL,
   'pts_vas', 'VAS pain', 1, NULL,
   'score', 'VAS score',
   'mm', 'decimal', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'narrative_only'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_koos', 'KOOS', 1, NULL,
   'pain', 'Pain subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_koos', 'KOOS', 1, NULL,
   'symptoms', 'Symptoms subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_koos', 'KOOS', 1, NULL,
   'adl', 'ADL subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_koos', 'KOOS', 1, NULL,
   'sport_rec', 'Sport & recreation subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_koos', 'KOOS', 1, NULL,
   'qol', 'QoL subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_hoos', 'HOOS', 2, NULL,
   'pain', 'Pain subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_hoos', 'HOOS', 2, NULL,
   'symptoms', 'Symptoms subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_hoos', 'HOOS', 2, NULL,
   'adl', 'ADL subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_hoos', 'HOOS', 2, NULL,
   'sport_rec', 'Sport & recreation subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_hoos', 'HOOS', 2, NULL,
   'qol', 'QoL subscale',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_acl_rsi', 'ACL-RSI', 3, NULL,
   'total_score', 'Total score',
   '0–100', 'decimal', FALSE,
   'higher'::direction_of_good_t, 'bar'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'on_publish'::client_portal_visibility_t, 'milestone'::client_view_chart_t),
  ('patient_reported', 'Patient-reported & pain', 10,
   'pts_region', 'Function — region specific', 2, NULL,
   'pts_tampa', 'Tampa Scale (kinesiophobia)', 4, NULL,
   'total_score', 'Total score',
   '17–68', 'integer', FALSE,
   'lower'::direction_of_good_t, 'line'::default_chart_t, 'vs_baseline'::comparison_mode_t,
   'never'::client_portal_visibility_t, 'hidden'::client_view_chart_t);

-- Record the schema version we just seeded.
INSERT INTO physical_markers_schema_version (id, schema_version, seeded_at)
VALUES (1, '1.1.0', now())
ON CONFLICT (id) DO UPDATE
  SET schema_version = EXCLUDED.schema_version,
      seeded_at      = EXCLUDED.seeded_at;
